Update docs for CosmWasm with Testnet
osmosis-labs/docs pull request #110
Opened 2022-06-07 06:39 UTC by Yoon-Suji

## What is the purpose of the change
This pull request improves documation of area `cosmwasm-testnet` by adding contents to deploying and executing CosmWasm smart contract on osmosis testnet.

## Brief change log
- Added content in `cosmwasm-testnet.md`

## Verifying this change
This change has been tested locally by rebuilding the doc website and verified content and links are expected

2022-06-08 07:28 UTC, sigridjineth commented
LGTM 👍 glad to your first contribution to web3 field

2022-06-08 07:29 UTC, sigridjineth approved these changes

2022-06-08 07:30 UTC, sigridjineth approved these changes
LGTM 👍 glad that your first contribution to web3/crypto field seems great!

2022-06-24 14:17 UTC, xBalbinus requested changes
Thanks so much for your great work. This all mostly looks good, see comments for some minor feedback.

2022-06-24 14:17 UTC, xBalbinus commented on developing/dapps/get_started/cosmwasm-testnet.md
> +You must participate in the [Osmosis discode](https://discord.com/invite/osmosis) to request a faucet of the Osmosis Testnet. After gaining access to the testnet channel on the `#roles` channel of th
```suggestion
You must participate in the [Osmosis discord](https://discord.com/invite/osmosis) to request a faucet of the Osmosis Testnet. After gaining access to the testnet channel on the `#roles` channel of the discord, you can request a testnet token by sending the following message on the `#faucet` channel:
```

2022-06-24 14:17 UTC, xBalbinus commented on developing/dapps/get_started/cosmwasm-testnet.md
> +For this example, we will use the [**cw-template**](https://github.com/InterWasm/cw-template) (CosmWasm Template) repo with counter example.
Osmosis actually has a cw_template https://github.com/osmosis-labs/cw-tpl-osmosis for you to use... the deploy process is also in the docs.

2022-06-24 14:17 UTC, xBalbinus commented on developing/dapps/get_started/cosmwasm-testnet.md
> + If you are using an operating system other than the one listed above, please refer to the [official document](https://stedolan.github.io/jq/download/).
```suggestion
If you are using an operating system other than the one listed above, please refer to the [official document](https://stedolan.github.io/jq/download/).
```

2022-06-24 14:46 UTC, Yoon-Suji commented
@xBalbinus Thank you for your kind comment! I made a new commit based on your comments. please check🙏

2022-07-01 17:43 UTC, closed without merging

2022-07-01 18:42 UTC, daniel-farina commented
@Yoon-Suji @sigridjineth 
Docs are live: https://docs.osmosis.zone/developing/dapps/get_started/cosmwasm-testnet-manual.html

Thank you so much